### ISSUE TITLE
Any Planned releases for this library?

### ISSUE THREAD

**Issue by bigmeech** [studioijeoma/p5.ijeoma.js#1]
Hi Ekene, I have been following you work right from processing and i'm excited at the fact that you have  created something for p5. I'm looking for an animation library to handle animation heavy lifting for p5. Is this mature enough?

**Comment by studioijeoma** [comment]
@bigmeech Thanks, amazing to hear! Yes, I hadn't thought to create a new release but I will soon. It's stable I'm just adding more documentation and examples. In the meantime just download them using the links and let me know what you think.

**Comment by studioijeoma** [comment]
@bigmeech btw just created the first release.

**Comment by bigmeech** [comment]
@ekeneijeoma Cool. Will have a look this weekend and play around with it. Nice work. Love it.
